/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MetaFinanceira;
import model.dao.MetaFinanceiraDAO;

/**
 *
 * @author CHARLES
 */
public class ListaMetaFinanceiraJF extends javax.swing.JFrame {
    
    MetaFinanceiraDAO dao;
    
    /**
     * Creates new form ListaMetaFinanceiraJF
     */
    public ListaMetaFinanceiraJF() {
        initComponents();
        dao = new MetaFinanceiraDAO();
        loadTabelaMetas();
    }
    
    public void loadTabelaMetas() {
    DefaultTableModel modelo = (DefaultTableModel) tblMetas.getModel();
    modelo.setNumRows(0);

    for (MetaFinanceira m : dao.listaMetas()) {
        Object[] linha = {
            m,
            m.getTitulo(),
            m.getDescricao(),
            m.getValorObjetivo(),
            m.getDataLimite(),
            m.getTipo(),
            m.getPrioridade()
        };
        modelo.addRow(linha);
    }
}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMetas = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblMetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMetas);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(30, 30, 30)
                        .addComponent(btnEditar)
                        .addGap(33, 33, 33)
                        .addComponent(btnRemover))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        
        CadastroMetaFinanceiraJD telaCadastro = new CadastroMetaFinanceiraJD(this, rootPaneCheckingEnabled);
        telaCadastro.setVisible(true);

        MetaFinanceira novo = telaCadastro.getMeta();
        if (novo != null) {
            try {
                dao.persist(novo);
                loadTabelaMetas();
            } catch (Exception ex) {
                System.err.println("Erro ao adicionar Meta de financeira: " + ex);
            }

        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        if (tblMetas.getSelectedRow() != -1) {
            MetaFinanceira obj = (MetaFinanceira) tblMetas.getModel().
                    getValueAt(tblMetas.getSelectedRow(), 0);
            int op_remover = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover " + obj + "?");
            if (op_remover == JOptionPane.YES_OPTION) {
                try {
                    dao.remover(obj);
                    JOptionPane.showMessageDialog(rootPane, "Usuario removido com sucesso... ");
                    loadTabelaMetas();
                } catch (Exception ex) {
                    System.err.println("Erro ao remover usuario: " + ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (tblMetas.getSelectedRow() != -1) {
            MetaFinanceira obj = (MetaFinanceira) tblMetas.getModel().
                    getValueAt(tblMetas.getSelectedRow(), 0);

            CadastroMetaFinanceiraJD telaEdicao = new CadastroMetaFinanceiraJD(this, rootPaneCheckingEnabled);
            telaEdicao.setMeta(obj);

            telaEdicao.setVisible(true);

            MetaFinanceira obj_retornado = telaEdicao.getMeta();

            if (obj_retornado != null) {

                try {
                    dao.persist(obj_retornado);
                    loadTabelaMetas();
                } catch (Exception ex) {
                    System.err.println("Erro ao editar Usuario: " + ex);
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Usuario");
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaMetaFinanceiraJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaMetaFinanceiraJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaMetaFinanceiraJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaMetaFinanceiraJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaMetaFinanceiraJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMetas;
    // End of variables declaration//GEN-END:variables
}
