/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CarteiraInvestimentos;
import model.dao.CarteiraInvestimentosDAO;

/**
 *
 * @author CHARLES
 */
public class ListaCarteiraJF extends javax.swing.JFrame {
    
    CarteiraInvestimentosDAO dao;
    
    /**
     * Creates new form ListaCarteiraJF
     */
    public ListaCarteiraJF() {
        initComponents();
        dao = new CarteiraInvestimentosDAO();
        loadTabelaCarteiras();
    }
    
    public void loadTabelaCarteiras() {
    DefaultTableModel modelo = (DefaultTableModel) tblCarteiras.getModel();
    modelo.setNumRows(0);

    for (CarteiraInvestimentos c : dao.listaCarteiras()) {
        Object[] linha = {
            c,
            c.getNome(),           // se tiver atributo nome
            c.getDescricao(),      // se tiver atributo descrição
            c.getUsuario().getNome() // nome do dono
        };
        modelo.addRow(linha);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarteiras = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblCarteiras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Carteira", "Nome", "Descricao", "Data Criacao", "Status", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarteiras);
        if (tblCarteiras.getColumnModel().getColumnCount() > 0) {
            tblCarteiras.getColumnModel().getColumn(1).setResizable(false);
            tblCarteiras.getColumnModel().getColumn(2).setResizable(false);
            tblCarteiras.getColumnModel().getColumn(3).setResizable(false);
            tblCarteiras.getColumnModel().getColumn(4).setResizable(false);
            tblCarteiras.getColumnModel().getColumn(5).setResizable(false);
        }

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(28, 28, 28)
                        .addComponent(btnRemover))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        CadastroCarteiraJD telaCadastro = new CadastroCarteiraJD(this, rootPaneCheckingEnabled);
        telaCadastro.setVisible(true);

        CarteiraInvestimentos novo = telaCadastro.getCarteira();
        if (novo != null) {
            try {
                dao.persist(novo);
                loadTabelaCarteiras();
            } catch (Exception ex) {
                System.err.println("Erro ao adicionar carteira: " + ex);
            }

        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (tblCarteiras.getSelectedRow() != -1) {
            CarteiraInvestimentos obj = (CarteiraInvestimentos) tblCarteiras.getModel().
                    getValueAt(tblCarteiras.getSelectedRow(), 0);
            int op_remover = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover " + obj + "?");
            if (op_remover == JOptionPane.YES_OPTION) {
                try {
                    dao.remover(obj);
                    JOptionPane.showMessageDialog(rootPane, "Usuario removido com sucesso... ");
                    loadTabelaCarteiras();
                } catch (Exception ex) {
                    System.err.println("Erro ao remover usuario: " + ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblCarteiras.getSelectedRow() != -1) {
            CarteiraInvestimentos obj = (CarteiraInvestimentos) tblCarteiras.getModel().
                    getValueAt(tblCarteiras.getSelectedRow(), 0);

            CadastroCarteiraJD telaEdicao = new CadastroCarteiraJD(this, rootPaneCheckingEnabled);
            telaEdicao.setCarteira(obj);

            telaEdicao.setVisible(true);

            CarteiraInvestimentos obj_retornado = telaEdicao.getCarteira();

            if (obj_retornado != null) {

                try {
                    dao.persist(obj_retornado);
                    loadTabelaCarteiras();
                } catch (Exception ex) {
                    System.err.println("Erro ao editar Usuario: " + ex);
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Usuario");
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCarteiraJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCarteiraJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCarteiraJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCarteiraJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaCarteiraJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarteiras;
    // End of variables declaration//GEN-END:variables
}
