/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author CHARLES
 */
public class PrincipalJF extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJF
     */
    public PrincipalJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        miUsuario = new javax.swing.JMenuItem();
        miCarteira = new javax.swing.JMenuItem();
        miInvestimento = new javax.swing.JMenuItem();
        miMetaFinanceira = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setText("Cadastro");

        miUsuario.setText("Usuario");
        miUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(miUsuario);

        miCarteira.setText("Carteira");
        miCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCarteiraActionPerformed(evt);
            }
        });
        menuCadastro.add(miCarteira);

        miInvestimento.setText("Investimento");
        miInvestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInvestimentoActionPerformed(evt);
            }
        });
        menuCadastro.add(miInvestimento);

        miMetaFinanceira.setText("Meta Financeira");
        miMetaFinanceira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMetaFinanceiraActionPerformed(evt);
            }
        });
        menuCadastro.add(miMetaFinanceira);

        jMenuBar1.add(menuCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioActionPerformed
        // TODO add your handling code here:
        ListaUsuarioJF telaUsuario = new ListaUsuarioJF();
        telaUsuario.setVisible(true);
    }//GEN-LAST:event_miUsuarioActionPerformed

    private void miCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCarteiraActionPerformed
        // TODO add your handling code here:
        ListaCarteiraJF telaCarteira = new ListaCarteiraJF();
        telaCarteira.setVisible(true);
    }//GEN-LAST:event_miCarteiraActionPerformed

    private void miInvestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInvestimentoActionPerformed
        // TODO add your handling code here:
        ListaInvestimentoJF telaInvestimento = new ListaInvestimentoJF();
        telaInvestimento.setVisible(true);
    }//GEN-LAST:event_miInvestimentoActionPerformed

    private void miMetaFinanceiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMetaFinanceiraActionPerformed
        // TODO add your handling code here:
        ListaMetaFinanceiraJF telaMetaFinanceira = new ListaMetaFinanceiraJF();
        telaMetaFinanceira.setVisible(true);
    }//GEN-LAST:event_miMetaFinanceiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem miCarteira;
    private javax.swing.JMenuItem miInvestimento;
    private javax.swing.JMenuItem miMetaFinanceira;
    private javax.swing.JMenuItem miUsuario;
    // End of variables declaration//GEN-END:variables
}
